### ISSUE TITLE
Rename and split package

### ISSUE THREAD

**Issue by flimzy** [go-kivik/kivik#178]
I'm creating this issue to inform kivik users of an upcoming change, and to invite comment.

My goal is to split the Kivik package up into sub-packages. This is to reduce the dependency tree, as well as to isolate changes to the sub-packages where they matter.

The new packages will be (roughly):

- **kivik** (plus **kivik/driver**), the core driver.
- **couchdb** The CouchDB backend (currently **kivik/driver/couchdb**)
- **pouchdb** The PouchDB backend (currently **kivik/driver/pouchdb**)
- **memorydb** The (in progress) memory backend (currently **kivik/driver/mem**)
- **fsdb** The (barely started) filesystem backend (currently **kivik/driver/fs**)
- **kouch** A command-line tool for interacting with CouchDB servers. (Partial support in **kivik/cmd/kivik**)
- **server** (name undecided) Libraries and possibly a command-line tool for running a Kivik server (currently **kivik/serve**)

Possibly concurrently, I would like to move all Kivik packages to the new [go-kivik](https://github.com/go-kivik) namespace.

My plan, such as it is, is to piecemeal _duplicate_ the existing Kivik components (**couchdb**, **pouchdb**, etc), into the new namespace. Changes will only be added to the new packages under the `go-kivik` namespace. This will allow existing installations to continue functioning during a transition period, while encouraging new users to use the new packages.

Eventually, likely after all sub-packages have been moved to `go-kivik`, I will take the plunge, and transfer the core `kivik` repository to the `go-kivik` namespace. GitHub will handle redirection, but that likely won't be sufficient, due to the `kivik/driver` sub-package.

Of course my goal is to make this transition as painless as possible.

Any comments or suggestions are welcome.

# TODO list

- [x] Move integration tests to [github.com/go-kivik/kiviktest](https://github.com/go-kivik/kiviktest)
- [x] Move PouchDB driver to [github.com/go-kivik/pouchdb](https://github.com/go-kivik/pouchdb)
- [x] Move CouchDB driver to [github.com/go-kivik/couchdb](https://github.com/go-kivik/couchdb)
- [x] Move Memory driver to [github.com/go-kivik/memorydb](https://github.com/go-kivik/memorydb)
- [x] Move Filesystem driver to [github.com/go-kivik/fsdb](https://github.com/go-kivik/fsdb)
- [x] Move proxy driver to [https://github.com/go-kivik/proxydb](https://github.com/go-kivik/proxydb)
- [x] Add deprecation* message to legacy PouchDB driver [#218]
- [x] Add deprecation* message to legacy CouchDB driver [#218]
- [x] Remove legacy PouchDB driver [#258]
- [x] Remove legacy CouchDB driver [#258]
- [x] Remove legacy Memory driver [#258]
- [x] Remove legacy Filesystem driver
- [x] Move server to [https://github.com/go-kivik/kivikd](https://github.com/go-kivik/kivikd) [#217]
- [x] Move command line tool to [https://github.com/go-kivik/kuery](https://github.com/go-kivik/kuery) [#259]

The final rename will involve:
- [x] Pin `kivik` and sub-packages to the old repo name [#260]
- [x] Move main Kivik package to `github.com/go-kivik/kivik`
- [x] Pin `kivik` and remaining sub-packages to the new repo name, with a 2.x tag.

*Once the new driver packages are published, I intend not to add any features or bugfixes to the legacy packages. After some time (probably 30-90 days or so), I'll add a single warning (probably in an `init` function) that warns that the driver is obsolete, and point to the new location.  Hopefully this will get the attention of anyone continuing to download the old location.  After a further wait, I will remove the legacy drivers entirely.

**Comment by flimzy** [comment]
The rename is finally complete. See [the announcement](http://kivik.io/preparing-for-rename)
