### ISSUE TITLE
Complete the memory driver

### ISSUE THREAD

**Issue by flimzy** [go-kivik/kivik#748]
Memory driver to do list:

- [x] Allow creating and destroying databases
- [x] Allow storing, fetching and deleting documents (https://github.com/flimzy/kivik/issues/141)
- [ ] Support attachments
- [ ] AllDocs
    - [x] Basic AllDocs queries (https://github.com/flimzy/kivik/issues/148)
    - [ ] Support `conflicts`
    - [ ] Support `descending`
    - [ ] Support `endkey`, `startkey` and `inclusive_end`
    - [ ] Support `include_docs`
    - [ ] Support `keys`
    - [ ] Support `limit` (https://github.com/flimzy/kivik/issues/167)
    - [ ] Support `skip`
    - [ ] Support `stale`
    - [ ] Support `update_seq`
- [x] BulkDocs (https://github.com/flimzy/kivik/issues/158)
- [x] Get/set Security
- [ ] Support Mango queries  (See also https://github.com/go-kivik/mango/milestone/1)
    - [x] Basic query support (https://github.com/flimzy/kivik/issues/166)
    - [ ] Support `limit`
    - [ ] Support `skip`
    - [ ] Support `sort`
    - [x] Support `fields` (https://github.com/flimzy/kivik/issues/169)
    - [ ] Support `use_index`
- [ ] Support Mango indexes
    - [ ] Create indexes
    - [ ] Query indexes
    - [ ] Delete indexes
- [ ] Support traditional views with indexes
- [ ] Support other traditional view functionality (reduce, list, etc)
- [ ] Changes feed
- [ ] Support replication
